-keep class android.hardware.camera2.** { *; }
-keep class android.media.ImageReader { *; }
-keep class android.hardware.camera2.params.StreamConfigurationMap { *; }
-keep class android.hardware.camera2.DngCreator { *; }
